export const Myprojects = [
    {
        "id": "1",
        "name": "PRODUKT NAVN",
        "about": "En produkt beskrivelse, med detaljer om proces og årsag til forskellige valg i designet ",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1699&q=80",
        tools: ["INDESIGN"],
      },
      {
        "id": "2",
        "name": "PRODUKT NAVN",
        "about": "En produkt beskrivelse, med detaljer om proces og årsag til forskellige valg i designet ",
        "image": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80",
        tools: ["XD", "CANVA"],
      },
      {
        "id": "3",
        "name": "PRODUKT NAVN",
        "about": "En produkt beskrivelse, med detaljer om proces og årsag til forskellige valg i designet ",
        "image": "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80",
        tools: ["PHOTOSHOP", "CANVA"],
      },
      {
        "id": "4",
        "name": "PRODUKT NAVN",
        "about": "En produkt beskrivelse, med detaljer om proces og årsag til forskellige valg i designet ",
        "image": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
        tools: ["XD"],
      },
      {
        "id": "5",
        "name": "PRODUKT NAVN",
        "about": "En produkt beskrivelse, med detaljer om proces og årsag til forskellige valg i designet ",
        "image": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1180&q=80",
        tools: ["PHOTOSHOP", "CANVA"],
      },
      {
        "id": "6",
        "name": "PRODUKT NAVN",
        "about": "En produkt beskrivelse, med detaljer om proces og årsag til forskellige valg i designet ",
        "image": "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
        tools: ["ILLUSTRATOR","PHOTOSHOP", "CANVA"],
      },
      {
        "id": "7",
        "name": "PRODUKT NAVN",
        "about": "En produkt beskrivelse, med detaljer om proces og årsag til forskellige valg i designet ",
        "image": "https://images.unsplash.com/photo-1570831739435-6601aa3fa4fb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1452&q=80",
        tools: ["PHOTOSHOP", "CANVA"],
      },
      {
        "id": "8",
        "name": "PRODUCT NAVN",
        "about": "En produkt beskrivelse, med detaljer om proces og årsag til forskellige valg i designet ",
        "image": "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=928&q=80",
        tools: ["PHOTOSHOP", "CANVA"],
      },
      {
        "id": "9",
        "name": "PRODUKT NAVN",
        "about": "En produkt beskrivelse, med detaljer om proces og årsag til forskellige valg i designet ",
        "image": "https://images.unsplash.com/photo-1580870069867-74c57ee1bb07?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
        tools: ["PHOTOSHOP", "CANVA"],
      },
      {
        "id": "10",
        "name": "PRODUKT NAVN",
        "about": "En produkt beskrivelse, med detaljer om proces og årsag til forskellige valg i designet ",
        "image": "https://images.unsplash.com/photo-1598460880248-71ec6d2d582b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=814&q=80",
        tools: ["PHOTOSHOP", "CANVA"],
      },
      {
        "id": "11",
        "name": "PRODUKT NAVN",
        "about": "En produkt beskrivelse, med detaljer om proces og årsag til forskellige valg i designet ",
        "image": "https://images.unsplash.com/photo-1570831739435-6601aa3fa4fb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1452&q=80",
        tools: ["PHOTOSHOP", "CANVA"],
      },
      {
        "id": "12",
        "name": "PRODUKT NAVN",
        "about": "En produkt beskrivelse, med detaljer om proces og årsag til forskellige valg i designet ",
        "image": "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=928&q=80",
        tools: ["PHOTOSHOP", "CANVA"],
      },


]
